# Configuration Nginx pour Next.js (Static Export)
server {
    listen 80;
    server_name wandertravel-event.com www.wandertravel-event.com;

    root /var/www/wandertravel-event.com/out;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Custom Error 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Basic Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml font/woff2;
}
